### ISSUE TITLE
DisconnectedException exception

### ISSUE THREAD

**Issue by mikkeljohnsen** [tmds/Tmds.DBus#128]
I keep getting this stack dump on macOS (running dotnet 6).

Has anyone seen this before, and know what the problem could be ?

macOS:
```
System.AggregateException: A Task's exception(s) were not observed either by
Waiting on the Task or accessing its Exception property. As a result, the
unobserved exception was rethrown by the finalizer thread. (Resource temporarily
unavailable)
 ---> Tmds.DBus.DisconnectedException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (35): Resource temporarily unavailable
   at Tmds.DBus.Transports.Transport.ReadCountAsync(Byte[] buffer, Int32 offset,
Int32 count, List`1 fileDescriptors)
   at Tmds.DBus.Transports.Transport.ReceiveMessageAsync()
   at Tmds.DBus.DBusConnection.ReceiveMessages(IMessageStream peer, Action`2
disconnectAction)
   --- End of inner exception stack trace ---
   at Tmds.DBus.Connection.ThrowIfNotConnected(Boolean disposed, ConnectionState
state, Exception disconnectReason)
   at Tmds.DBus.Connection.ThrowIfNotConnected()
   at Tmds.DBus.Connection.GetConnectedConnection()
   at Tmds.DBus.Connection.GetConnectionTask()
   at Tmds.DBus.Connection.WatchSignalAsync(ObjectPath path, String interface,
String signalName, SignalHandler handler)
   at Tmds.DBus.CodeGen.DBusObjectProxy.WatchNonVoidSignalAsync[T](String iface,
String member, Action`1 error, Action`1 action, ReadMethodDelegate`1 readValue,
Boolean isPropertiesChanged)
   --- End of inner exception stack trace ---
```

Windows:
```
System.AggregateException: A Task's exception(s) were not observed either by
Waiting on the Task or accessing its Exception property. As a result, the
unobserved exception was rethrown by the finalizer thread. (Unexpected reply
message received: MessageType = 'Error', ReplySerial = 72)
 ---> Tmds.DBus.DisconnectedException: Unexpected reply message received:
MessageType = 'Error', ReplySerial = 72
 ---> Tmds.DBus.ProtocolException: Unexpected reply message received:
MessageType = 'Error', ReplySerial = 72
   at Tmds.DBus.DBusConnection.HandleMessage(Message msg, IMessageStream peer)
   at Tmds.DBus.DBusConnection.ReceiveMessages(IMessageStream peer, Action`2
disconnectAction)
   --- End of inner exception stack trace ---
   at Tmds.DBus.Connection.ThrowIfNotConnected(Boolean disposed, ConnectionState
state, Exception disconnectReason)
   at Tmds.DBus.Connection.ThrowIfNotConnected()
   at Tmds.DBus.Connection.GetConnectedConnection()
   at Tmds.DBus.Connection.GetConnectionTask()
   at Tmds.DBus.Connection.WatchSignalAsync(ObjectPath path, String interface,
String signalName, SignalHandler handler)
   at Tmds.DBus.CodeGen.DBusObjectProxy.WatchNonVoidSignalAsync[T](String iface,
String member, Action`1 error, Action`1 action, ReadMethodDelegate`1 readValue,
Boolean isPropertiesChanged)
   --- End of inner exception stack trace ---
================================================
```

**Comment by mikkeljohnsen** [comment]
It seems that Tmds.DBus make dbus-daemon crash on windows and mac. I used "DBusSharp" before changing to Tmds.DBus and did not see dbus-daemon crash.

**Comment by tmds** [comment]
> System.Net.Sockets.SocketException (35)

The library has some specific handling for EAGAIN, but the value for EAGAIN on mac (`35`) doesn't match the hard-coded value for Linux at:

https://github.com/tmds/Tmds.DBus/blob/29c59521ef162cd59c1119fc180f5708c6cb8db2/src/Tmds.DBus/Transports/TransportSocket.cs#L27

Try working around the issue by setting `SupportsFdPassing` to `false` for your client.

https://github.com/tmds/Tmds.DBus/blob/29c59521ef162cd59c1119fc180f5708c6cb8db2/src/Tmds.DBus/ClientSetupResult.cs#L33
