### ISSUE TITLE
Netplan-Dbus hitting Error

### ISSUE THREAD

**Issue by alberk8** [tmds/Tmds.DBus#148]
I have tried to get netplan in Ubuntu to work but  GetAsync of the io.netplan.Netplan.Config is quitting with exception.  it seems that the  error is coming from Tmds.Dbus.
[netplan readme](https://github.com/canonical/netplan/blob/main/doc/netplan-dbus.md)
[netplan conf](https://github.com/canonical/netplan/blob/main/dbus/io.netplan.Netplan.conf)

OS: Ubuntu 20.04
.Net 6

**Code**
```
var netplan = Connection.System.CreateProxy<INetplan>("io.netplan.Netplan", "/io/netplan/Netplan");

var config = await netplan.ConfigAsync();
Console.WriteLine("Config: " + config);

var netplan1 = Connection.System.CreateProxy<IConfig>("io.netplan.Netplan.Config", config );
var getplan = await netplan1.GetAsync();
```

**Generated Dbus Code**
```
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Tmds.DBus;

[assembly: InternalsVisibleTo(Tmds.DBus.Connection.DynamicAssemblyName)]
namespace DbusX.Netplan
{
    [DBusInterface("io.netplan.Netplan")]
    interface INetplan : IDBusObject
    {
        Task<bool> ApplyAsync();
        Task<bool> GenerateAsync();
        Task<(string, object)[]> InfoAsync();
        Task<ObjectPath> ConfigAsync();
    }

    [DBusInterface("io.netplan.Netplan.Config")]
    interface IConfig : IDBusObject
    {
        Task<bool> ApplyAsync();
        Task<string> GetAsync();
        Task<bool> SetAsync(string arg0, string arg1);
        Task<bool> TryAsync(uint arg0);
        Task<bool> CancelAsync();
    }
}
```

**Exception**
```
Config: /io/netplan/Netplan/config/OOYAK1
Unhandled exception. System.ArgumentException: Property Get method System.Threading.Tasks.Task`1[System.String] GetAsync() must accept a 'string' parameter and return 'Task<object>'
   at Tmds.DBus.CodeGen.TypeDescription.AddInterfaceDescription(Type type, DBusInterfaceAttribute interfaceAttribute, List`1 interfaces)
   at Tmds.DBus.CodeGen.TypeDescription.Describe(Type type, Boolean isInterfaceType)
   at Tmds.DBus.CodeGen.DBusObjectProxyTypeBuilder.Build(Type interfaceType)
   at Tmds.DBus.CodeGen.DynamicAssembly.GetProxyTypeInfo(Type interfaceType)
   at Tmds.DBus.Connection.CreateProxy(Type interfaceType, String busName, ObjectPath path)
   at Tmds.DBus.Connection.CreateProxy[T](String serviceName, ObjectPath path)
   at Program.<Main>$(String[] args) in /home/smart/dbusdisk/DbusDisk/Program.cs:line 26
   at Program.<Main>(String[] args)
```

**Comment by tmds** [comment]
```
Property Get method System.Threading.Tasks.Task`1[System.String] GetAsync() must accept a 'string' parameter and return 'Task<object>'
```
By convention, `Tmds.DBus` thinks the `GetAsync` method is for properties and should have an `object` return type.
You should be able to specify some other method name by setting `DBusInterface.GetPropertyMethod`.
