### ISSUE TITLE
Codegen cannot be used with wildcards

### ISSUE THREAD

**Issue by daniol** [tmds/Tmds.DBus#157]
The basic examples of codegen suggest that it supports generating code from several XML files using a wildcard (*.xml).

However, this does not work currently (at least in Windows), as it produces an IO exception:

```dotnet dbus codegen interfaces/*.xml```
or 
```dotnet dbus codegen interfaces\*.xml```

```
Unhandled exception. System.AggregateException: One or more errors occurred. (The filename, directory name, or volume label syntax is incorrect. : 'C:\Projects\dbus_test\interfaces\*.xml')
  ---> System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Projects\dbus_test\interfaces\*.xml'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Tmds.DBus.Tool.CodeGenCommand.GenerateCodeAsync(CodeGenArguments codeGenArguments) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/CodeGenCommand.cs:line 175
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Tmds.DBus.Tool.CodeGenCommand.Execute() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/CodeGenCommand.cs:line 87
   at Tmds.DBus.Tool.Command.<.ctor>b__4_1() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Command.cs:line 17
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Tmds.DBus.Tool.Program.Main(String[] args) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Program.cs:line 15
```

**Expected behavior**

Option 1) It works, support for wildcards is available as stated in the documentation
Option 2) The documentation should note that only one file is possible, without suggesting wildcard works

**Comment by tmds** [comment]
The program accepts multiple files.
A unix shell expands `/usr/share/dbus-1/interfaces/*.xml` to the matching files, and the tool gets the list of files as input.

If your shell doesn't expand this, you can still specify multiple filenames manually.

**Comment by tmds** [comment]
I'm going to close this, as it isn't the tool that expands the wildcards in the example.
