### ISSUE TITLE
How to create a new project on Windows10?

### ISSUE THREAD

**Issue by f3404923** [tmds/Tmds.DBus#168]
I want to make a app. run on Raspiberry Pi 3b(System is debian).
My computer is win10 x64 OS and .net core 6.0 sdk.
It was some exception happend when I follow your tips create a console app at"
dotnet dbus list services --bus system | grep NetworkManager
org.freedesktop.NetworkManager". 

It still exception ocurred when I attempt run "dotnet dbus list". The error message as below:
```
Unhandled exception. System.ArgumentNullException: type (Parameter 'Type argument is required.')
   at Tmds.DBus.Tool.ListCommand.Execute() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/ListCommand.cs:line 39
   at Tmds.DBus.Tool.Command.<.ctor>b__4_1() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Command.cs:line 17
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Tmds.DBus.Tool.Program.Main(String[] args) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Program.cs:line 15
```

I have no idea to solve it, can you help me?

**Comment by tmds** [comment]
```
dotnet dbus list services --bus system | grep NetworkManager
```
This is a Linux shell command.

Are you executing this on your rpi?
If you try to run it on your Windows machine using PowerShell, it won't work.

**Comment by f3404923** [comment]
OK，I‘ill  try it again after migrate my code to unbuntu.
Thanks
