### ISSUE TITLE
DBus Cannot assign requested address

### ISSUE THREAD

**Issue by Jeremy-Code-F** [tmds/Tmds.DBus#174]
Hi, I'm trying to utilize this library to interact with org.freedesktop.secrets

I've generated my file with codegen

```
dotnet dbus list services | grep secrets
org.freedesktop.secrets
```

```dotnet dbus codegen --service org.freedesktop.secrets```

In the generated secrets.DBus.cs file I'm trying to call 

```
DBusInterface("org.freedesktop.Secret.Collection")]
    public interface ICollection : IDBusObject
    {
        ...
        Task<CollectionProperties> GetAllAsync(); // this
        ...
    }
```

```
var systemConnection = Connection.System;
            var collectionProxy = systemConnection.CreateProxy<ICollection>("org.freedesktop.Secret.Collection", "/org/freedesktop/secrets/collection/Default");
            var collections = collectionProxy.GetAllAsync().Result;
            Console.WriteLine(collections);
```

But I get an exception when it calls ```var collections = collectionProxy.GetAllAsync().Result;```

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot assign requested address)
 ---> Tmds.DBus.ConnectException: Cannot assign requested address
 ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP)
   at Tmds.DBus.Transports.TransportSocket.ConnectAsync(EndPoint endPoint)
   at Tmds.DBus.Transports.TransportSocket.ConnectUnixAsync(AddressEntry entry, CancellationToken cancellationToken, Boolean supportsFdPassing)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Tmds.DBus.Transports.TransportSocket.ConnectUnixAsync(AddressEntry entry, CancellationToken cancellationToken, Boolean supportsFdPassing)
   at Tmds.DBus.Transports.TransportSocket.ConnectAsync(AddressEntry entry, CancellationToken cancellationToken, Boolean supportsFdPassing)
   at Tmds.DBus.Transports.Transport.ConnectAsync(AddressEntry entry, ClientSetupResult connectionContext, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Tmds.DBus.Transports.Transport.ConnectAsync(AddressEntry entry, ClientSetupResult connectionContext, CancellationToken cancellationToken)
   at Tmds.DBus.DBusConnection.ConnectAsync(ClientSetupResult connectionContext, Boolean runContinuationsAsynchronously, Action`1 onDisconnect, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Tmds.DBus.DBusConnection.ConnectAsync(ClientSetupResult connectionContext, Boolean runContinuationsAsynchronously, Action`1 onDisconnect, CancellationToken cancellationToken)
   at Tmds.DBus.Connection.DoConnectAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Tmds.DBus.Connection.DoConnectAsync()
   at Tmds.DBus.Connection.GetConnectionTask()
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   at secrets.DBus.ICollectionProxy.GetAllAsync()
   at LibSecretDriver.Program.Main(String[] args) in /home/chewy/RiderProjects/LibSecretDriver/LibSecretDriver/Program.cs:line 15
--- End of stack trace from previous location ---
   at Tmds.DBus.Transports.TransportSocket.ConnectUnixAsync(AddressEntry entry, CancellationToken cancellationToken, Boolean supportsFdPassing)
   at Tmds.DBus.Transports.Transport.ConnectAsync(AddressEntry entry, ClientSetupResult connectionContext, CancellationToken cancellationToken)
   at Tmds.DBus.DBusConnection.ConnectAsync(ClientSetupResult connectionContext, Boolean runContinuationsAsynchronously, Action`1 onDisconnect, CancellationToken cancellationToken)
   at Tmds.DBus.Connection.DoConnectAsync()
   --- End of inner exception stack trace ---
   at Tmds.DBus.Connection.DoConnectAsync()
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at LibSecretDriver.Program.Main(String[] args) in /home/chewy/RiderProjects/LibSecretDriver/LibSecretDriver/Program.cs:line 15
```

Apologies if I'm missing something obvious, pretty new to DBus in general

Pop!_OS 22.04 x64
Gnome 42.2

**Comment by Jeremy-Code-F** [comment]
Resolved - Instead of going directly to ICollection, go to IService and start a session which allows you to get to the collections

```
var secretProperties = _secretService.GetAllAsync().Result;
        ObjectPath? targetCollection = null;
        foreach (var collection in secretProperties.Collections)
        {
            if (collection.ToString().EndsWith(collectionName))
            {
                targetCollection = collection;
                break;
            }
        }

        if (targetCollection == null)
        {
            throw new ArgumentException($"No collection found with the name {collectionName}");
        }

        List<ObjectPath> objectsToUnlock = new List<ObjectPath>();
        objectsToUnlock.Add((ObjectPath)targetCollection);
        // var res = _secretService.UnlockAsync(objectsToUnlock).Result;
        
        var collectionProxy = _connection.CreateProxy<ICollection>("org.freedesktop.secrets", (ObjectPath)targetCollection);
        var collRes = collectionProxy.GetAllAsync().Result;
        foreach (var collItem in collRes.Items)
        {
            
            var res = _secretService.UnlockAsync(new ObjectPath[]{collItem}).Result;
            var itemProxy = _connection.CreateProxy<IItem>("org.freedesktop.secrets", collItem);
            string name = itemProxy.GetAsync<string>("Label").Result;
            var secret = itemProxy.GetSecretAsync(sessionObject).Result;
            var str = Encoding.Default.GetString(secret.Item3);
            return str;
        }
```
