### ISSUE TITLE
Problem in signals with complex ValueTuples<T>

### ISSUE THREAD

**Issue by emanuelebeliart** [tmds/Tmds.DBus#206]
Hello,

I'm trying to use Tmds.DBus with a Cpp application.
A lot of functions are working well both calling method either in signalling.
Using complex ValueTuple<T> like: "ValueTuple<(tring, string, string, int, int, string, string, string, string, string, int, bool, string)> audioItem" received in signal calls then task become apparently blocked.
I'm use to developing in cpp and c# is a new world for me hence i apologize for bad dev.

This is how DBus.cs is generated with codegen and an xml:

`Task<IDisposable> WatchAudioItemAsync(Action<(ValueTuple<int> source, ValueTuple<(string, string, string, int, int, string, string, string, string, string, int, bool, string)> audioItem)> handler, Action<Exception> onError = null);`

The desired target to be received is:
```
signal time=1682495303.240440 sender=:1.107 -> destination=(null destination) serial=22578 path=/MultimediaManager; interface=com.art.multimediamanager.interface; member=audiolist
  
 struct
 {
      int32 1
  }
struct
 {
      string "setAbsoluteFilePath"
      string "setFileName"
      string "setThumbnailAbsoluteFilePath"
      int32 0
      int32 0
      string "setAlbum"
      string "setArtist"
      string "setTitle"
      string "setGenre"
      string "setFrontCoverAbsoluteFilePath"
      int32 1000
      boolean false
      string ""
   }
```

This is how i set up the task to listen and send data to another application:
```
public async void ThreadShell()
        {
            Console.WriteLine("HMIManagerDbusInterfaceTestApp threadShell");

            var client = Connection.Session;
            var multiMediaManagerProxy = client.CreateProxy<IMultimediaManagerInterface>(MultiMediaManagerTypesClass.SERVICE_NAME, MultiMediaManagerTypesClass.OBJECT_PATH);
            
            // Connect signals
            Task.Run(async () => await multiMediaManagerProxy.WatchAudioItemAsync(onAudioListChanged() =>Console.WriteLine("onMediaSourceChanged Progress" + onMediaSourceChanged) )).Wait();
    

            var storageSource = ValueTuple.Create((int)MultiMediaManagerTypesClass.MediaSources.MEDIA_HDD);


            while(_isRunning)
            {
                PrintMenu();
                char ch = Console.ReadKey().KeyChar;
                switch(ch)
                {
                    case '1':
                        Console.WriteLine("\n1 - isMultimediaReady");
                        var isMultimediaReady = await multiMediaManagerProxy.isMultimediaReadyAsync();
                        Console.WriteLine("isMultimediaReady: " + isMultimediaReady);
                        break;
                    case '2':
                        Console.WriteLine("\n2 - CanPlayAudio");
                        var CanPlayAudio = await multiMediaManagerProxy.CanPlayAudioAsync();
                        Console.WriteLine("CanPlayAudio: " + CanPlayAudio);
                        break;
                    case '3':
                        Console.WriteLine("\n3 - GetStorageSourceConnectionState");
                        var storageState = await multiMediaManagerProxy.GetStorageSourceConnectionStateAsync(storageSource);
                        Console.WriteLine("GetStorageSourceConnectionStateAsync: " + storageState);
                        break;
                    case '4':
                        Console.WriteLine("\n4 - IsStorageSourceKnownAsync");
                        var IsStorageSourceKnown = await multiMediaManagerProxy.IsStorageSourceKnownAsync(storageSource);
                        Console.WriteLine("IsStorageSourceKnown: " + IsStorageSourceKnown);
                        break;
                    case 'q':
                        _isRunning = false;
                        break;
                    default:
                        Console.WriteLine("\nUNKNOWN");
                        break;

                }

            }
        }
```

I also tried to use a class declaration likes:
```
Task<IDisposable> WatchAudioItemAsync(int source, **AudioItem** audioItem)> handler, Action<Exception> onError = null);
```
but compare an error likes this:
```
Unhandled exception. System.ArgumentException: Cannot (de)serialize Type 'MultiMediaManagerTypes.AudioItem'
   at Tmds.DBus.Signature.GetSig(Type type, Boolean isCompileTimeType)
   at Tmds.DBus.CodeGen.TypeDescription.InspectParameterType(Type parameterType, ParameterInfo parameter, Nullable`1& signature, IList`1& arguments)
   at Tmds.DBus.CodeGen.TypeDescription.AddInterfaceDescription(Type type, DBusInterfaceAttribute interfaceAttribute, List`1 interfaces)
   at Tmds.DBus.CodeGen.TypeDescription.Describe(Type type, Boolean isInterfaceType)
   at Tmds.DBus.CodeGen.TypeDescription.DescribeInterface(Type type)
   at Tmds.DBus.CodeGen.DBusObjectProxyTypeBuilder.Build(Type interfaceType)
   at Tmds.DBus.CodeGen.DynamicAssembly.GetProxyTypeInfo(Type interfaceType)
   at Tmds.DBus.Connection.CreateProxy(Type interfaceType, String busName, ObjectPath path)
   at Tmds.DBus.Connection.CreateProxy[T](String serviceName, ObjectPath path)
   at HMIManagerDbusInterface.HMIManagerDbusInterfaceTestApp.ThreadShell() in /home/ubuntu/CSharpTests/dbus/portingMultiMediaManager/multimediamanager/HMIManagerDbusInterfaceTestApp.cs:line 95
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Can anyone help me please?

1. Why with ValueTuple<T> task is blocked?
2. How can i create a class and deserialize using the class that describe the properties and not with the ValueTuple<T>?

Many Thanks in advance

**Comment by emanuelebeliart** [comment]
I've solved the problem easily using AudioItem Object but as a struct instead a class:
```
public struct AudioItem
    {
        public string AbsoluteFilePath           ;
        public string FileName                   ;
        public string ThumbnailAbsoluteFilePath  ;
        public int    favourite                  ;
        public int    channel                    ;
        public string album                      ;
        public string artist                     ;
        public string title                      ;
        public string genre                      ;
        public string frontCoverAbsoluteFilePath ;
        public int    duration                   ;
        public bool   isPlaylist                 ;                                     
        public string plPath                     ;     
    }
```
