### ISSUE TITLE
Crashing Mono when scanning devices in a C# .NET Framework 4.8 WinForms app running on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by DougShuffield** [tmds/Tmds.DBus#214]
Device: Raspberry Pi 3B+
OS: Raspbian GNU/Linux 11 (bullseye) 32-bit
Mono: 6.12.0.200
Bluez: 5.55
.NET Framework: 4.8
Tmds.DBus: 0.11.0 (this the version  Linux.Bluetooth is currently using)
Linux.Bluetooth: 5.64.0

I am attempting to make a simple WinForms app with a single button that scans for and prints Bluetooth devices to the console using [Linux.Bluetooth](https://github.com/SuessLabs/Linux.Bluetooth) which uses Tmds.DBus under the hood. As soon as adapter.StartDiscoveryAsync() is called it crashes mono with a SIGSEGV. I am posting here as the underlying error seems to be occurring in Tmds.DBus based on the gdb debug information on the crash in Mono. I have plans to use Linux.Bluetooth at a larger scale, but not until I can get this very simple example working correctly and robustly.

Any help would be much appreciated. Let me know if you need any additional information.

Here is the code from Form1.cs:
```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Linux.Bluetooth;
using Linux.Bluetooth.Extensions;

namespace scan
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private async void button1_Click(object sender, EventArgs e)
        {
            int scanSeconds = 5;

            IAdapter1 adapter = (await BlueZManager.GetAdaptersAsync()).FirstOrDefault();

            var adapterPath = adapter.ObjectPath.ToString();
            var adapterName = adapterPath.Substring(adapterPath.LastIndexOf("/") + 1);
            Console.WriteLine($"Using Bluetooth adapter {adapterName}");
            Console.WriteLine($"Adapter's full path:    {adapterPath}");

            Console.WriteLine("Starting discovery...");
            await adapter.StartDiscoveryAsync();
            Console.WriteLine("Delaying 5 seconds...");
            await Task.Delay(TimeSpan.FromSeconds(scanSeconds));
            Console.WriteLine("Stopping discovery...");
            await adapter.StopDiscoveryAsync();

            // Print out the devices we already know about.
            Console.WriteLine();
            Console.WriteLine("Getting devices...");
            var devices = await adapter.GetDevicesAsync();
            foreach (var device in devices)
            {
                string deviceDescription = await GetDeviceDescriptionAsync(device);
                Console.WriteLine($" - {deviceDescription}");
            }

        }
        private static async Task<string> GetDeviceDescriptionAsync(IDevice1 device)
        {
            var deviceProperties = await device.GetAllAsync();
            return $"{deviceProperties.Alias} (Address: {deviceProperties.Address}, RSSI: {deviceProperties.RSSI})";
        }
    }
}
```
And here is the gdb debug info on the crash:
```
(gdb) run --debug scan.exe
Starting program: /usr/bin/mono --debug scan.exe
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x75fff400 (LWP 17834)]
[New Thread 0x743bc400 (LWP 17835)]
[New Thread 0x716e5400 (LWP 17836)]
[New Thread 0x713ff400 (LWP 17837)]
[New Thread 0x710ff400 (LWP 17838)]
[New Thread 0x70dff400 (LWP 17839)]
[New Thread 0x70aff400 (LWP 17840)]
[New Thread 0x707ff400 (LWP 17841)]
[New Thread 0x704ff400 (LWP 17842)]
[New Thread 0x703fe400 (LWP 17843)]
[New Thread 0x702fd400 (LWP 17844)]
Using Bluetooth adapter hci0
Adapter's full path:    /org/bluez/hci0
Starting discovery...
Delaying 5 seconds...
[New Thread 0x701fc400 (LWP 17846)]

Thread 9 "Thread Pool Wor" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x707ff400 (LWP 17841)]
0x00000000 in ?? ()
(gdb) where
#0  0x00000000 in ?? ()
#1  0x715c3748 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) p (char*)mono_pmip (0x715c3748)
[Thread 0x702fd400 (LWP 17844) exited]
[Thread 0x710ff400 (LWP 17838) exited]
$2 = 0x7052ed40 " (wrapper delegate-invoke) Tmds.DBus.CodeGen.ReadMethodDelegate`1<Tmds.DBus.PropertyChanges>:invoke_T_MessageReader (Tmds.DBus.Protocol.MessageReader) [{0x7051e510} + 0xf0]  (0x715c3658 0x715c38d8) [0"...
```

**Comment by tmds** [comment]
There's been other issues with Mono, like https://github.com/tmds/Tmds.DBus/issues/155.
We never got to the bottom of those.

Can you use .NET 6 or later?

It's likely that will just work.

**Comment by DougShuffield** [comment]
Thanks for the quick response.  We are trying to use an older WinForms app, so I am unsure I can without doing a significant rewrite, but I will look into it. 
I see in #155 that you mention using Tmds.DBus.Protocol as a possible solution.  Since I am using Tmds.DBus through another Nuget tool, Linux.Bluetooth, I will have to investigate how involved it might be to make that happen. Any other suggestions you might have for making this work are appreciated.

**Comment by tmds** [comment]
>  We are trying to use an older WinForms app

Are you running the WinForms app on the rpi3 with Mono?

> I see in https://github.com/tmds/Tmds.DBus/issues/155 that you mention using Tmds.DBus.Protocol as a possible solution.

The protocol library doesn't use emit/reflection, so it shouldn't trigger the Mono issue.
Changing to the protocol library will also be quite an effort.

**Comment by tmds** [comment]
Closing due to inactivity.
