### ISSUE TITLE
Codegen throws on invalid signatures

### ISSUE THREAD

**Issue by SteffenSH** [tmds/Tmds.DBus#248]
The following `codegen` command fails:

`$ dotnet dbus codegen --bus system --service org.bluez`

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Tmds.DBus.Tool.Generator.ParseType(String dbusType, Int32& index, List`1 elementNames) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 295
   at Tmds.DBus.Tool.Generator.ParseType(String dbusType, List`1 elementNames) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 284
   at Tmds.DBus.Tool.Generator.InArgToParameter(XElement argXml, Int32 idx) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 364
   at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.SeparatedList[TNode](IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsParameterList(IEnumerable`1 parameters)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.MethodDeclaration(String name, IEnumerable`1 parameters, IEnumerable`1 typeParameters, SyntaxNode returnType, Accessibility accessibility, DeclarationModifiers modifiers, IEnumerable`1 statements)
   at Tmds.DBus.Tool.Generator.MethodDeclaration(XElement methodXml) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 266
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsInterfaceMembers(IEnumerable`1 members)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.InterfaceDeclaration(String name, IEnumerable`1 typeParameters, Accessibility accessibility, IEnumerable`1 interfaceTypes, IEnumerable`1 members)
   at Tmds.DBus.Tool.Generator.InterfaceDeclaration(String name, XElement interfaceXml) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 114
   at Tmds.DBus.Tool.Generator.DBusInterfaceDeclaration(String name, XElement interfaceXml)+MoveNext() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 88
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Tmds.DBus.Tool.Generator.Generate(IEnumerable`1 interfaceDescriptions) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 75
   at Tmds.DBus.Tool.CodeGenCommand.GenerateCodeAsync(CodeGenArguments codeGenArguments) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/CodeGenCommand.cs:line 194
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Tmds.DBus.Tool.CodeGenCommand.Execute() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/CodeGenCommand.cs:line 115
   at Tmds.DBus.Tool.Command.<.ctor>b__4_1() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Command.cs:line 17
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Tmds.DBus.Tool.Program.Main(String[] args) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Program.cs:line 16
```

The following gives more context to the problem...
This happens on a Raspberry Pi 4

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

Bluetooth experimental features have been enabled to allow reception of Bluetooth Low Energy (BLE) advertisement messages. Enable it by editing file `/lib/systemd/system/bluetooth.service` and change 
this line: `ExecStart=/usr/libexec/bluetooth/bluetoothd`
to this: `ExecStart=/usr/libexec/bluetooth/bluetoothd --experimental`
Then restart bluetooth:
```
$ sudo systemctl daemon-reload
$ sudo systemctl restart bluetooth
```

```
$ dotnet --version
8.0.201
```

```
$ dotnet tool list -g
Package Id          Version      Commands
--------------------------------------------
tmds.dbus.tool      0.16.0       dotnet-dbus
```

```
$ dotnet dbus list objects --bus system --service org.bluez
/ : org.freedesktop.DBus.ObjectManager
/org/bluez : org.bluez.AgentManager1 org.bluez.HealthManager1 org.bluez.ProfileManager1
/org/bluez/hci0 : org.bluez.Adapter1 org.bluez.AdvertisementMonitorManager1 org.bluez.BatteryProviderManager1 org.bluez.GattManager1 org.bluez.LEAdvertisingManager1 org.bluez.Media1 org.bluez.NetworkServer1 org.bluez.SimAccess1
/org/bluez/test : org.bluez.SimAccessTest1
```
(The `org.bluez.SimAccessTest1` interface is part of the Debian / Raspberry OS distribution but only visible in experimental mode).

```
$ dbus-send --system --print-reply --dest=org.bluez /org/bluez/test org.freedesktop.DBus.Introspectable.Introspect
method return time=1708832005.094954 sender=:1.94 -> destination=:1.188 serial=156 reply_serial=2
   string "
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
    <interface name="org.freedesktop.DBus.Introspectable">
        <method name="Introspect">
            <arg name="xml" type="s" direction="out" />
        </method>
    </interface>
    <interface name="org.bluez.SimAccessTest1">
        <method name="OngoingCall">
            <arg name="ongoing" type="b" direction="in" />
        </method>
        <method name="MaxMessageSize">
            <arg name="size" type="u" direction="in" />
        </method>
        <method name="DisconnectImmediate"></method>
        <method name="CardStatus">
            <arg name="status" type="" direction="in" />
        </method>
    </interface>
</node>
"
```

As can be seen the `CardStatus` method has an argument `status` that is declaring a malformed `type=""` which causes the dotnet `System.IndexOutOfRangeException`.

The codegen should preferably wrap the exception with a more descriptive message.
E.g. in file `src\Tmds.DBus.Tool\Generator.cs`, in method: `private SyntaxNode ParseType(string dbusType, ref int index, List<string> elementNames = null)` the exception could be wrapped like this when validating it's arguments:
`if (index >= dbusType.Length) { throw new NotSupportedException($"Invalid dbus type '{dbusType}'"); }`

Or even better if the codegen tool is more resilient, by just outputting a warning that tells the user in what path/interface/method/arg/type the problem originate and just interpret the malformed type as `v` (varaiant).

**Comment by tmds** [comment]
Yes, the command shouldn't crash for bad type signatures and give a meaningful error message instead.

@SteffenSH do you want to make a PR to implement this?

**Comment by SteffenSH** [comment]
@tmds :thumbsup: ok I will try to find some time and take a shot at it
