### ISSUE TITLE
"Object reference not set to an instance of an object" on TransportSocket.ReadAsync 

### ISSUE THREAD

**Issue by charleslales** [tmds/Tmds.DBus#41]
Hi,

I faced (and tried to fix) a NullReferenceException on TransportSocket.ReadAsync because of readContext.Tcs null (l239) when ReadCompleted fired too quickly.

Complete stacktrace:
   at Tmds.DBus.Transports.TransportSocket.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, List`1 fileDescriptors) in C:\Tools\DEV\scmrepos\Tmds.DBus-master\src\Tmds.DBus\Transports\TransportSocket.cs:line 239
   at Tmds.DBus.Transports.Transport.<ReadCountAsync>d__11.MoveNext() in C:\Tools\DEV\scmrepos\Tmds.DBus-master\src\Tmds.DBus\Transports\Transport.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Tmds.DBus.Transports.Transport.<ReadLineAsync>d__19.MoveNext() in C:\Tools\DEV\scmrepos\Tmds.DBus-master\src\Tmds.DBus\Transports\Transport.cs:line 335
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Tmds.DBus.Transports.Transport.<SendAuthCommand>d__17.MoveNext() in C:\Tools\DEV\scmrepos\Tmds.DBus-master\src\Tmds.DBus\Transports\Transport.cs:line 294
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Tmds.DBus.Transports.Transport.<SendAuthCommands>d__16.MoveNext() in C:\Tools\DEV\scmrepos\Tmds.DBus-master\src\Tmds.DBus\Transports\Transport.cs:line 280
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Tmds.DBus.Transports.Transport.<DoClientAuth>d__15.MoveNext() in C:\Tools\DEV\scmrepos\Tmds.DBus-master\src\Tmds.DBus\Transports\Transport.cs:line 248
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Tmds.DBus.Transports.Transport.<ConnectAsync>d__7.MoveNext() in C:\Tools\DEV\scmrepos\Tmds.DBus-master\src\Tmds.DBus\Transports\Transport.cs:line 40

Fixed it with 
return readContext.Tcs != null ? readContext.Tcs.Task : Task.FromResult(_receiveData.BytesTransferred);
.. but 1. not sure at all, 2. how can I submit (since coming from solution setup for net452?

To give more info:
- 2 tools try to exchange through DBus one same machine Win7
- tool1 starts dbus-daemon.exe with its own process / config file
- once done, tool1 try (but fail) to connect to DBus with "var conn1 = new Connection(dbusDaemon.Address)"
- then tool2 will publish command, event & co on DBus 

Kind regards,
Charles

**Comment by tmds** [comment]
The code on master looks like this:
```C#
                readContext.Tcs = readContext.Tcs ?? new TaskCompletionSource<int>();
                _receiveData.SetBuffer(buffer, offset, count);
                readContext.FileDescriptors = fileDescriptors;
                if (!_socket.ReceiveAsync(_receiveData))
                {
                    if (_receiveData.SocketError == SocketError.Success)
                    {
                        return Task.FromResult(_receiveData.BytesTransferred);
                    }
                    else
                    {
                        return Task.FromException<int>(new SocketException((int)_receiveData.SocketError));
                    }
                }
                else
                {
                    return readContext.Tcs.Task;
```
The first line assigns readContext.Tcs when it is null. Is this also the case for your code/version?

**Comment by charleslales** [comment]
Yes, check bellow what fixed it.

                var readContext = _receiveData.UserToken as ReadContext;
                readContext.Tcs = readContext.Tcs ?? new TaskCompletionSource<int>();
                _receiveData.SetBuffer(buffer, offset, count);
                readContext.FileDescriptors = fileDescriptors;
                if (!_socket.ReceiveAsync(_receiveData)) // I/O operation completed synchronously
                {
                    if (_receiveData.SocketError == SocketError.Success)
                    {
                        return Task.FromResult(_receiveData.BytesTransferred);
                    }
                    else
                    {
                        return TaskFromException.Create<int>(new SocketException((int)_receiveData.SocketError));
                    }
                }
                else // I/O operation is pending
                {
                    //return readContext.Tcs.Task;
                    return readContext.Tcs != null ?
                        readContext.Tcs.Task :
                        Task.FromResult(_receiveData.BytesTransferred);
                }

It is like (on localhost) between your test "readContext.Tcs ??" and "return readContext.Tcs.Task;" readContext.Tcs is set to null.
To me it was because of ReadCompleted with "readContext.Tcs = null;" too quickly called..

**Comment by tmds** [comment]
I see, the operation is asynchronous but ReadCompleted runs before we get to the end of the function.
The fix is to assign the TaskCompletionSource to a local variable and use that at the end.
```C#
var tcs = readContext.Tcs = readContext.Tcs ?? new TaskCompletionSource<int>();
```
and
```C#
return tcs.Task;
```

**Comment by tmds** [comment]
The same fix is needed a bit lower.

Do you want to make a PR with the fix?

**Comment by charleslales** [comment]
Same issue with SendBufferListAsync.. but one more time, not sure at all about the fix :-o

            var sendContext = _sendArgs.UserToken as SendContext;
            sendContext.Tcs = sendContext.Tcs ?? new TaskCompletionSource<object>();
            _sendArgs.BufferList = bufferList;
            if (!_socket.SendAsync(_sendArgs)) // I/O operation completed synchronously
            {
                if (_sendArgs.SocketError == SocketError.Success)
                {
                    return TaskCompletedTask.Create();
                }
                else
                {
                    return TaskFromException.Create(new SocketException((int)_sendArgs.SocketError));
                }
            }
            else // I/O operation is pending
            {
                //return sendContext.Tcs.Task;
                return sendContext.Tcs != null ?
                    sendContext.Tcs.Task :
                    TaskCompletedTask.Create();
            }

**Comment by charleslales** [comment]
Haven't see your post before, cool that you see / can explain what is best solution!

**Comment by tmds** [comment]
This describes the steps to fork, clone, make changes and create a PR: https://guides.github.com/activities/forking/.
If you have some issues during the steps, feel free to ask them here.

**Comment by tmds** [comment]
This is in 0.6.0 on nuget.org.
