### ISSUE TITLE
dot net code gen doesn't work due to exception

### ISSUE THREAD

**Issue by omayhemo** [tmds/Tmds.DBus#69]
Neither

```
$ dotnet dbus list services --bus system | grep NetworkManager
org.freedesktop.NetworkManager
$ dotnet dbus list objects --bus system --service org.freedesktop.NetworkManager | head -2
/org/freedesktop : org.freedesktop.DBus.ObjectManager
/org/freedesktop/NetworkManager : org.freedesktop.NetworkManager
```

nor 

`$ dotnet dbus codegen --bus system --service org.freedesktop.NetworkManager`

Both result in the following exception.  Therefor the readme tutorial is quite useless.

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Value cannot be null.
Parameter name: address) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: address
   at Tmds.DBus.Connection..ctor(String address, ConnectionOptions connectionOptions)
   at Tmds.DBus.Tool.ListCommand.ListServicesAsync(String address)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Tmds.DBus.Tool.ListCommand.Execute()
   at Tmds.DBus.Tool.Command.<.ctor>b__4_1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Tmds.DBus.Tool.Program.Main(String[] args)
```

**Comment by tmds** [comment]
> Value cannot be null.
Parameter name: address

It looks like the address for the system bus is null on your system.
What does this output: `Console.WriteLine(Tmds.DBus.Address.System)` ?

**Comment by tmds** [comment]
Closing due to inactivity.

**Comment by f3404923** [comment]
Re Open this one.
Console.WriteLine(Tmds.DBus.Address.System);
It is return 'null'. 
My  computer is Win10 x64, .net core 6.0

**Comment by tmds** [comment]
> My computer is Win10 x64, .net core 6.0

Are you running a D-Bus daemon on your Windows machine?

**Comment by f3404923** [comment]
Yes, I can run it.
```
E:\source_code\C_Sharp\RaspIot>dotnet dbus


Usage: dotnet-dbus [options] [command]

Options:
  -h|--help  Show help information

Commands:
  codegen
  list

Use "dotnet-dbus [command] --help" for more information about a command.


E:\source_code\C_Sharp\RaspIot>dotnet dbus list
Unhandled exception. System.ArgumentNullException: type (Parameter 'Type argument is required.')
   at Tmds.DBus.Tool.ListCommand.Execute() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/ListCommand.cs:line 39
   at Tmds.DBus.Tool.Command.<.ctor>b__4_1() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Command.cs:line 17
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Tmds.DBus.Tool.Program.Main(String[] args) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Program.cs:line 15
```
