### ISSUE TITLE
TargetInvocationException with InnerException == null

### ISSUE THREAD

**Issue by kekekeks** [tmds/Tmds.DBus#70]
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.) ---> Tmds.DBus.DBusException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at dbusmenudump.Program.Main(String[] args) in /home/kekekeks/Projects/dbusmenudump/dbusmenudump/Program.cs:line 53
```

It's kinda hard to tell what's wrong if there is just plain TargetInvocationException being thrown from somewhere.

**Comment by kekekeks** [comment]
Actually, it was a swallowed "Cannot send null variant" on the server side

**Comment by tmds** [comment]
@kekekeks I agree this isn't a helpful exception.
Do you know where the original exception was thrown (the one that is wrapped by the `TargetInvocationException`)?

**Comment by kekekeks** [comment]
I was trying to return `null` from a method that should be returning dbus variant. The library actually throws a relevant exception in serialization code, but it gets replaced by TargetInvocationException which gets sent to the client.

**Comment by kekekeks** [comment]
https://github.com/tmds/Tmds.DBus/blob/eb2899f449681c3ed238f0c9000e8d16614027a5/src/Tmds.DBus/Protocol/MessageWriter.cs#L320

**Comment by tmds** [comment]
Can you get a stacktrace (set a breakpoint, or print Environment.StackTrace)?

**Comment by tmds** [comment]
Closing due to inactivity.
