### ISSUE TITLE
DBus.Tool doesn't handle missing argument for list

### ISSUE THREAD

**Issue by voltagex** [tmds/Tmds.DBus#72]
```
pi@raspberrypi:~/publish $ ./dotnet-dbus list

Unhandled Exception: System.ArgumentNullException: type
Parameter name: Type argument is required.
   at Tmds.DBus.Tool.ListCommand.Execute() in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\ListCommand.cs:line 39
   at Tmds.DBus.Tool.Command.<.ctor>b__4_1() in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\Command.cs:line 17
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Tmds.DBus.Tool.Program.Main(String[] args) in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\Program.cs:line 15

```

```
pi@raspberrypi:~/publish $ ./dotnet-dbus list services

Unhandled Exception: System.AggregateException: One or more errors occurred. (Value cannot be null.
Parameter name: address) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: address
   at Tmds.DBus.ClientConnectionOptions..ctor(String address) in C:\git\Tmds.DBus\src\Tmds.DBus\ClientConnectionOptions.cs:line 25
   at Tmds.DBus.Connection..ctor(String address) in C:\git\Tmds.DBus\src\Tmds.DBus\Connection.cs:line 131
   at Tmds.DBus.Tool.ListCommand.<ListServicesAsync>d__14.MoveNext() in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\ListCommand.cs:line 174
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Tmds.DBus.Tool.ListCommand.Execute() in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\ListCommand.cs:line 43
   at Tmds.DBus.Tool.Command.<.ctor>b__4_1() in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\Command.cs:line 17
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Tmds.DBus.Tool.Program.Main(String[] args) in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\Program.cs:line 15
```

**Comment by tmds** [comment]
@voltagex do you want to send a PR to fix this?

**Comment by voltagex** [comment]
Yes, but I don't know when I'll get to it.

**Comment by tmds** [comment]
Closing because I don't plan to fix this myself and the issue has been sitting idle.
