### ISSUE TITLE
DBus.Tool codegen shouldn't crash on permission denied

### ISSUE THREAD

**Issue by voltagex** [tmds/Tmds.DBus#73]
```
pi@raspberrypi:~/publish $ ./dotnet-dbus codegen --bus system --service org.bluez

Unhandled Exception: System.AggregateException: One or more errors occurred. (org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.23" (uid=1000 pid=1632 comm="./dotnet-dbus codegen --bus system --service org.b") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (uid=0 pid=424 comm="/usr/lib/bluetooth/bluetoothd ")) ---> Tmds.DBus.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.23" (uid=1000 pid=1632 comm="./dotnet-dbus codegen --bus system --service org.b") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination="org.bluez" (uid=0 pid=424 comm="/usr/lib/bluetooth/bluetoothd ")
   at Tmds.DBus.DBusConnection.<CallMethodAsync>d__56.MoveNext() in C:\git\Tmds.DBus\src\Tmds.DBus\DBusConnection.cs:line 907
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Tmds.DBus.Connection.<CallMethodAsync>d__69.MoveNext() in C:\git\Tmds.DBus\src\Tmds.DBus\Connection.cs:line 1020
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Tmds.DBus.CodeGen.DBusObjectProxy.<SendMethodReturnReaderAsync>d__12.MoveNext() in C:\git\Tmds.DBus\src\Tmds.DBus\CodeGen\DBusObjectProxy.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Tmds.DBus.CodeGen.DBusObjectProxy.<CallNonVoidMethodAsync>d__9`1.MoveNext() in C:\git\Tmds.DBus\src\Tmds.DBus\CodeGen\DBusObjectProxy.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Tmds.DBus.NodeVisitor.<VisitAsyncInternal>d__2.MoveNext() in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\NodeVisitor.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Tmds.DBus.Tool.CodeGenCommand.<GenerateCodeAsync>d__15.MoveNext() in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\CodeGenCommand.cs:line 164
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Tmds.DBus.Tool.CodeGenCommand.Execute() in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\CodeGenCommand.cs:line 97
   at Tmds.DBus.Tool.Command.<.ctor>b__4_1() in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\Command.cs:line 17
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Tmds.DBus.Tool.Program.Main(String[] args) in C:\git\Tmds.DBus\src\Tmds.DBus.Tool\Program.cs:line 15

```

**Comment by tmds** [comment]
@voltagex do you want to send a PR to fix this?

**Comment by voltagex** [comment]
Having a look at this tonight. Would you prefer it fixed in the command line tool or in the library (custom exception maybe?)

**Comment by tmds** [comment]
Closing because I don't plan to fix this myself and the issue has been sitting idle.
