### ISSUE TITLE
How use CloseSafeHandle to open stream or socket? 

### ISSUE THREAD

**Issue by MrRadian** [tmds/Tmds.DBus#89]
That's probably a silly question, but how do i use the file descriptor CloseSafehandle to open a stream or socket? I am trying to use FileStream with DangerousGetHandle () but I am getting the error:
```
System.IO.IOException: The process cannot access the file because it is being used by another process.
at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
at System.IO.FileStream.ReadNative(Span`1 buffer)
at System.IO.FileStream.ReadSpan(Span`1 destination)
at System.IO.FileStream.Read(Span`1 buffer)
```

**Comment by tmds** [comment]
This tests may have the answer you are looking for: https://github.com/tmds/Tmds.DBus/blob/eb2899f449681c3ed238f0c9000e8d16614027a5/test/Tmds.DBus.Tests/DaemonTests.cs#L260.

If it doesn't, can you share some code that shows what you want to do?

**Comment by tmds** [comment]
@MrRadian did the test answer your question?

**Comment by tmds** [comment]
Closing due to inactivity.
